apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-order
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Grupo-202-FIAP/ms-order
    targetRevision: main
    path: infra/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
